export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
};
const About = () => {
    return (
        <main>
          

            {/* About Content */}
            <section className="py-20">
                <div className="max-w-7xl mx-auto px-5 grid md:grid-cols-2 gap-10 items-center">
                    <div>
                        <img
                            src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f"
                            alt="About"
                            className="rounded-xl shadow-lg w-full"
                        />
                    </div>

                    <div>
                        <h2 className="text-4xl font-bold mb-5">Who We Are</h2>

                        <p className="text-gray-600 mb-4">
                            We specialize in web development, UI/UX design, and digital
                            solutions. Our goal is to build high-quality products that
                            provide value to our clients and users.
                        </p>

                        <p className="text-gray-600">
                            With years of experience in React, Next.js, Node.js, and modern
                            technologies, we deliver fast, secure, and scalable applications.
                        </p>
                    </div>
                </div>
            </section>

            {/* Stats Section */}
            <section className="bg-blue-600 text-white py-16">
                <div className="max-w-7xl mx-auto px-5 grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
                    <div>
                        <h3 className="text-4xl font-bold">500+</h3>
                        <p>Projects</p>
                    </div>

                    <div>
                        <h3 className="text-4xl font-bold">200+</h3>
                        <p>Clients</p>
                    </div>

                    <div>
                        <h3 className="text-4xl font-bold">10+</h3>
                        <p>Years Experience</p>
                    </div>

                    <div>
                        <h3 className="text-4xl font-bold">24/7</h3>
                        <p>Support</p>
                    </div>
                </div>
            </section>

            {/* Team Section */}
            <section className="py-20">
                <div className="max-w-7xl mx-auto px-5">
                    <h2 className="text-4xl font-bold text-center mb-12">
                        Our Team
                    </h2>

                    <div className="grid md:grid-cols-3 gap-8">
                        {["John Doe", "Sarah Smith", "Michael Lee"].map((member) => (
                            <div
                                key={member}
                                className="shadow-lg rounded-xl p-6 text-center hover:shadow-xl transition"
                            >
                                <img
                                    src="https://via.placeholder.com/150"
                                    alt={member}
                                    className="w-32 h-32 rounded-full mx-auto mb-4"
                                />

                                <h3 className="text-xl font-semibold">{member}</h3>
                                <p className="text-gray-500">Web Developer</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
        </main>
    );
}

export default About
