export const metadata = {
    title: "Contact Page",
    description: "Generated by create next app",
};
const Contact = () => {
    return (
        <main className="max-w-7xl mx-auto px-5 py-16">
            {/* Heading */}
            <div className="text-center mb-12">
                <h1 className="text-5xl font-bold mb-4">Contact Us</h1>
                <p className="text-gray-600 max-w-2xl mx-auto">
                    Have a question or want to work with us? Fill out the form below and
                    we'll get back to you as soon as possible.
                </p>
            </div>

            <div className="grid md:grid-cols-2 gap-10">
                {/* Contact Info */}
                <div className="space-y-6">
                    <div className="p-6 border rounded-xl">
                        <h2 className="text-2xl font-semibold mb-2">Address</h2>
                        <p className="text-gray-600">
                            123 Business Street, Jaipur, Rajasthan
                        </p>
                    </div>

                    <div className="p-6 border rounded-xl">
                        <h2 className="text-2xl font-semibold mb-2">Email</h2>
                        <p className="text-gray-600">info@example.com</p>
                    </div>

                    <div className="p-6 border rounded-xl">
                        <h2 className="text-2xl font-semibold mb-2">Phone</h2>
                        <p className="text-gray-600">+91 9876543210</p>
                    </div>
                </div>

                {/* Contact Form */}
                <form className="border rounded-xl p-6 space-y-5">
                    <div>
                        <label className="block mb-2 font-medium">Name</label>
                        <input
                            type="text"
                            placeholder="Enter your name"
                            className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                        />
                    </div>

                    <div>
                        <label className="block mb-2 font-medium">Email</label>
                        <input
                            type="email"
                            placeholder="Enter your email"
                            className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                        />
                    </div>

                    <div>
                        <label className="block mb-2 font-medium">Subject</label>
                        <input
                            type="text"
                            placeholder="Enter subject"
                            className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                        />
                    </div>

                    <div>
                        <label className="block mb-2 font-medium">Message</label>
                        <textarea
                            rows="5"
                            placeholder="Write your message..."
                            className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                        ></textarea>
                    </div>

                    <button
                        type="submit"
                        className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700"
                    >
                        Send Message
                    </button>
                </form>
            </div>
        </main>
    );
}

export default Contact
