
export const metadata = {
    title: "Product Page",
    description: "Generated by create next app",
};



const Product = () => {
    const products = [
        {
            id: 1,
            name: "Wireless Headphones",
            price: "$99",
            image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6572/6572447_sd.jpg",
        },
        {
            id: 2,
            name: "Smart Watch",
            price: "$149",
            image: "https://m.media-amazon.com/images/I/61ZjlBOp+rL._SL1500_.jpg",
        },
        {
            id: 3,
            name: "Laptop",
            price: "$899",
            image: "https://tse4.mm.bing.net/th/id/OIP.4H_H2w1rWgfVDu5yQWRmGAAAAA?w=300&h=250&rs=1&pid=ImgDetMain&o=7&rm=3",
        },
        {
            id: 4,
            name: "Gaming Mouse",
            price: "$49",
            image: "https://tse4.mm.bing.net/th/id/OIP.9FhaSPdYRP3PpfK_ZWorPQHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
        },
        {
            id: 5,
            name: "Keyboard",
            price: "$59",
            image: "https://tse4.mm.bing.net/th/id/OIP.55lveOGj6vvMk1Qn6VqpCQHaDp?rs=1&pid=ImgDetMain&o=7&rm=3",
        },
        {
            id: 6,
            name: "Monitor",
            price: "$299",
            image: "https://tse3.mm.bing.net/th/id/OIP.zSKLAA-CQ2DSi-IaA3U2jAHaHa?w=700&h=700&rs=1&pid=ImgDetMain&o=7&rm=3",
        },
    ];





    return (
        <main className="max-w-7xl  mx-auto px-5 py-16">
            {/* Heading */}
            <div className="text-center mb-12">
                <h1 className="text-5xl font-bold mb-4">Our Products</h1>
                <p className="text-gray-600 max-w-2xl mx-auto">
                    Discover our latest collection of high-quality products designed to
                    enhance your daily life.
                </p>
            </div>

            {/* Search */}
            <div className="mb-10">
                <input
                    type="text"
                    placeholder="Search products..."
                    className="w-full border rounded-lg px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                />
            </div>

            {/* Product Grid */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
                {products.map((product) => (
                    <div
                        key={product.id}
                        className="border rounded-xl overflow-hidden shadow-md hover:shadow-xl transition"
                    >
                        <img
                            src={product.image}
                            alt={product.name}
                            className="w-full  p-2 h-64 object-contain " 
                        />

                        <div className="p-5">
                            <h2 className="text-xl font-semibold mb-2">
                                {product.name}
                            </h2>

                            <p className="text-2xl font-bold text-blue-600 mb-4">
                                {product.price}
                            </p>

                            <button className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700">
                                Add to Cart
                            </button>
                        </div>
                    </div>
                ))}
            </div>
        </main>
    );
}

export default Product
