export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};


const Home = () => {
  return (
    <div>
     

      {/* Hero Section */}
      <section className="bg-gray-100 min-h-[80vh] flex items-center">
        <div className="max-w-7xl mx-auto px-5 grid md:grid-cols-2 gap-10 items-center">
          <div>
            <h2 className="text-5xl font-bold mb-4">
              Build Amazing Websites
            </h2>

            <p className="text-gray-600 mb-6">
              Create modern, responsive, and beautiful websites using React,
              Next.js, and Tailwind CSS.
            </p>

            <div className="flex gap-4">
              <button className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700">
                Get Started
              </button>

              <button className="border border-gray-400 px-6 py-3 rounded-lg hover:bg-gray-200">
                Learn More
              </button>
            </div>
          </div>

          <div>
            <img
              src="https://images.unsplash.com/photo-1498050108023-c5249f4df085"
              alt="Hero"
              className="rounded-xl shadow-lg"
            />
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-5">
          <h2 className="text-4xl font-bold text-center mb-12">
            Our Features
          </h2>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="shadow-lg p-6 rounded-xl">
              <h3 className="text-xl font-semibold mb-3">
                Fast Development
              </h3>
              <p className="text-gray-600">
                Build projects quickly using modern tools and frameworks.
              </p>
            </div>

            <div className="shadow-lg p-6 rounded-xl">
              <h3 className="text-xl font-semibold mb-3">
                Responsive Design
              </h3>
              <p className="text-gray-600">
                Works perfectly on mobile, tablet, and desktop devices.
              </p>
            </div>

            <div className="shadow-lg p-6 rounded-xl">
              <h3 className="text-xl font-semibold mb-3">
                Easy Customization
              </h3>
              <p className="text-gray-600">
                Customize everything according to your requirements.
              </p>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}

export default Home
